easy_admin:
  site_name: Conference Guestbook
    design:
        menu:
          - { route: 'homepage', label: 'Back to the website', icon: 'home' }
          - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
          - { entity: 'Comment', label: 'Comments', icon: 'comments' }

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        Comment:
        - App\Entity\Comment
        list:
          fields:
            - author
            - { property: 'email', type: 'email' }
            - { property: 'createdAt', type: 'datetime' }
          sort: ['createdAt', 'ASC']
          filters: ['conference']
          edit:
            fields:
              - { property: 'conference' }
              - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
              - 'author'
              - { property: 'email', type: 'email' }
              - text
        Conference:
        - App\Entity\Conference
